apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  # Add your application spec here...

  postSync:
    resources: 
      - group: ""
        kind: Pod
        name: demo
    manifest:
      apiVersion: v1
      kind: Pod
      metadata:
        name: demo
      spec:
        containers:
          - name: check-deployment
            image: alpine
            command: ["sh", "-c", "check-deployment.sh"]
            restartPolicy: OnFailure
    ignoreErrors: true

